---
title: "Reproducible Research Week 2 Project"
author: "Keval Bhavsar"
date: "02/06/2020"
output: html_document
---

# Loading and Preprocessing the Data  
Load the data Process/transform the data (if necessary) into a format suitable for your analysis
```{R}

# download file from web
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", destfile = "activity.zip", mode="wb")

# unzip data and read 
unzip("activity.zip")
stepdata <- read.csv("activity.csv", header = TRUE)
head(stepdata)
```

# What is Mean Total Number of Steps Taken Per Day?
#### 1. Calculate Total Number of Steps Taken Each Day
```{R}
library(magrittr)
library(dplyr)

databydate <- stepdata %>% select(date, steps) %>% group_by(date) %>% summarize(tsteps= sum(steps)) %>%na.omit()

```
##### 2. Creating Histrogram
```{R}
hist(databydate$tsteps, xlab = "Total daily Steps",main="Histogram of Total Steps by day", breaks = 20)
```

#### 3. Calculate and Report the Mean and Median of the Total Number of Steps Taken Per Day
```{R}
mean(databydate$tsteps)
```
```{R}
median(databydate$tsteps)
```

# What is the average daily activity pattern?
#### 1. Time Series Plot
```{R}

library(ggplot2)

databyinterval <- stepdata%>% select(interval, steps) %>% na.omit() %>% group_by(interval) %>% summarize(tsteps= mean(steps)) 
ggplot(databyinterval, aes(x=interval, y=tsteps))+ geom_line()

```

#### 2. The 5-Minute Interval that, on Average, Contains the Maximum Number of Steps

```{R}
databyinterval[which(databyinterval$tsteps== max(databyinterval$tsteps)),]
```

# Imputing Missing Values
#### 1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

```{R}
# generate listing of NA's
missingVals <- sum(is.na(data))
```
```{R}
missingVals
```

#### 2 & 3. Devise a strategy for filling in all of the missing values in the dataset, and Making a New Dataset
I will use the mean for that 5 -minute interval to replace all the missing values in the dataset. At the end, I will check if all the NAs have been replaced

```{R}
library(magrittr)
library(dplyr)

replacewithmean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
meandata <- stepdata%>% group_by(interval) %>% mutate(steps= replacewithmean(steps))
head(meandata)
```

#### 4. Making histogram of the total number of steps taken each day and Calculating the mean and median total number of steps taken per day.

```{R}
FullSummedDataByDay <- aggregate(meandata$steps, by=list(meandata$date), sum)

names(FullSummedDataByDay)[1] ="date"
names(FullSummedDataByDay)[2] ="totalsteps"
head(FullSummedDataByDay,15)
```

Summary of New data : Mean & Median
```{R}
summary(FullSummedDataByDay)
```

Making a histogram
```{R}
hist(FullSummedDataByDay$totalsteps, xlab = "Steps", ylab = "Frequency", main = "Total Daily Steps", breaks = 20)
```

Compare the mean and median of Old and New data
```{R}
oldmean <- mean(databydate$tsteps, na.rm = TRUE)
newmean <- mean(FullSummedDataByDay$totalsteps)

# Old mean and New mean
oldmean
```
```{R}
newmean
```
```{R}
oldmedian <- median(databydate$tsteps, na.rm = TRUE)
newmedian <- median(FullSummedDataByDay$totalsteps)

# Old median and New median
oldmedian
```
```{R}
newmedian
```

# Differences in Activity Patterns Between Weekdays and Weekends
```{R}
meandata$date <- as.Date(meandata$date)
meandata$weekday <- weekdays(meandata$date)
meandata$weekend <- ifelse(meandata$weekday=="Saturday" | meandata$weekday=="Sunday", "Weekend", "Weekday" )

library(ggplot2)
meandataweekendweekday <- aggregate(meandata$steps , by= list(meandata$weekend, meandata$interval), na.omit(mean))
names(meandataweekendweekday) <- c("weekend", "interval", "steps")

ggplot(meandataweekendweekday, aes(x=interval, y=steps, color=weekend)) + geom_line()+
facet_grid(weekend ~.) + xlab("Interval") + ylab("Mean of Steps") +
    ggtitle("Comparison of Average Number of Steps in Each Interval")
```